services:
  apidb:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./apidb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      apidb:
        condition: service_healthy

  db-init:
    build: ./backend
    env_file:
      - .env
    entrypoint: /bin/bash
    command:
      - -c
      - |
        python manage.py migrate
    depends_on:
      apidb:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/frontend
    command: npm start

volumes:
  apidb:
    driver: local
